name: Test Action

on:
  issues:
    types: [opened, edited, closed, reopened]
  
  issue_comment:
    types: [created, edited, deleted]

jobs:
  debug:
    name: Debug (${github.event_name})
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo '${{ toJSON(github) }}' > debug-${github.event_name}.json
      
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: debug-${github.event_name}.json